language: go
go:
  - "1.11.x"
  - "1.10.x"

services:
  - postgresql

before_script:
  - psql -c "create database migration_test;" -U postgres
  - psql -c "create user migration_test with password 'migration_test';" -U postgres
  - psql -c "grant all privileges on database migration_test to migration_test;" -U postgres

install:
  - go get github.com/jjeffery/sqlr/private/scanner
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3

script:
  - go test -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
